env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
# rules: {}
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  #quotes: off
    # - avoidEscape: true
  #implicit-arrow-linebreak: off
